name: e2e:feature
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    run: |
      echo "$github.event_name"
      echo "$github.event.deployment_status.state.url"
    # only runs this job on successful deploy
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.url, 'unleash-monorepo-frontend')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          env: AUTH_USER=admin,AUTH_PASSWORD=unleash4all
          config: baseUrl=${{ github.event.deployment_status.target_url }}
          spec: cypress/integration/feature/feature.spec.ts
